version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes: [ mongo-data:/data/db ]

  redis:
    image: redis:7
    restart: unless-stopped
    ports: ["6379:6379"]

  api:
    build: .
    depends_on: [ mongo, redis ]
    env_file: .env
    ports: ["8000:8000"]
    volumes:
      - .:/code           # live‑reload while developing

volumes:
  mongo-data:
